from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import csv
import json

VECTORS = 64
HEADER_CHECKSUM_OFFSET = 0x18E

VECTOR_NAMES = [
    "initial_ssp",
    "reset_pc",
    "bus_error",
    "address_error",
    "illegal_instruction",
    "divide_by_zero",
    "chk_exception",
    "trapv_exception",
    "privilege_violation",
    "trace_exception",
    "line_1010_emulator",
    "line_1111_emulator",
    "reserved_12",
    "reserved_13",
    "reserved_14",
    "uninitialized_interrupt",
    "reserved_16",
    "reserved_17",
    "reserved_18",
    "reserved_19",
    "reserved_20",
    "reserved_21",
    "reserved_22",
    "reserved_23",
    "spurious_interrupt",
    "irq_level_1",
    "irq_level_2",
    "irq_level_3",
    "irq_level_4_hblank",
    "irq_level_5",
    "irq_level_6_vblank",
    "irq_level_7",
    "trap_0",
    "trap_1",
    "trap_2",
    "trap_3",
    "trap_4",
    "trap_5",
    "trap_6",
    "trap_7",
    "trap_8",
    "trap_9",
    "trap_10",
    "trap_11",
    "trap_12",
    "trap_13",
    "trap_14",
    "trap_15",
    "reserved_48",
    "reserved_49",
    "reserved_50",
    "reserved_51",
    "reserved_52",
    "reserved_53",
    "reserved_54",
    "reserved_55",
    "reserved_56",
    "reserved_57",
    "reserved_58",
    "reserved_59",
    "reserved_60",
    "reserved_61",
    "reserved_62",
    "reserved_63",
]


def _be16(buf: bytes, offset: int) -> int:
    return (buf[offset] << 8) | buf[offset + 1]


def _be32(buf: bytes, offset: int) -> int:
    return (
        (buf[offset] << 24)
        | (buf[offset + 1] << 16)
        | (buf[offset + 2] << 8)
        | buf[offset + 3]
    )


def _put_be16(buf: bytearray, offset: int, value: int) -> None:
    buf[offset] = (value >> 8) & 0xFF
    buf[offset + 1] = value & 0xFF


@dataclass
class RomHeader:
    console_name: str
    domestic_title: str
    overseas_title: str
    serial: str
    checksum: int
    rom_start: int
    rom_end: int


def compute_genesis_checksum(data: bytes) -> int:
    """Genesis checksum: 16-bit BE sum of words from offset 0x200 to EOF."""
    total = 0
    for i in range(0x200, len(data), 2):
        hi = data[i]
        lo = data[i + 1] if i + 1 < len(data) else 0
        total = (total + ((hi << 8) | lo)) & 0xFFFF
    return total


def with_updated_header_checksum(data: bytes) -> bytes:
    out = bytearray(data)
    _put_be16(out, HEADER_CHECKSUM_OFFSET, compute_genesis_checksum(data))
    return bytes(out)


class GenesisRom:
    def __init__(self, path: Path):
        self.path = Path(path)
        self.data = self.path.read_bytes()
        if len(self.data) < 0x200:
            raise ValueError("ROM too small for Mega Drive header")

    def parse_header(self) -> RomHeader:
        b = self.data
        return RomHeader(
            console_name=b[0x100:0x110].decode("ascii", errors="replace").rstrip(),
            domestic_title=b[0x120:0x150].decode("ascii", errors="replace").rstrip(),
            overseas_title=b[0x150:0x180].decode("ascii", errors="replace").rstrip(),
            serial=b[0x180:0x18E].decode("ascii", errors="replace").rstrip(),
            checksum=_be16(b, HEADER_CHECKSUM_OFFSET),
            rom_start=_be32(b, 0x1A0),
            rom_end=_be32(b, 0x1A4),
        )

    def computed_checksum(self) -> int:
        return compute_genesis_checksum(self.data)

    def read_vectors(self) -> list[int]:
        return [_be32(self.data, i * 4) for i in range(VECTORS)]

    def write_chunks(self, out_dir: Path, chunk_size: int = 0x4000) -> list[str]:
        out_dir.mkdir(parents=True, exist_ok=True)
        names = []
        for idx in range(0, len(self.data), chunk_size):
            name = f"chunk_{idx:06X}.bin"
            (out_dir / name).write_bytes(self.data[idx : idx + chunk_size])
            names.append(name)
        return names


def write_symbols_csv(path: Path, vectors: list[int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["name", "address", "note"])
        for i, addr in enumerate(vectors):
            label = VECTOR_NAMES[i] if i < len(VECTOR_NAMES) else f"vec_{i:03d}"
            w.writerow([label, f"0x{addr:08X}", "autogenerated from vector table"])


def write_vector_asm(path: Path, vectors: list[int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["; Autogenerated Genesis vector labels", "cpu 68000", "", "Vectors:"]
    for i, addr in enumerate(vectors):
        lines.append(f"    dc.l vec_{i:03d} ; 0x{addr:08X}")
    lines.append("")
    for i, addr in enumerate(vectors):
        lines.append(f"vec_{i:03d}: ; ROM 0x{addr:08X}")
        lines.append("    ; TODO: replace with disassembly")
        lines.append("    rts")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def write_manifest(path: Path, header: RomHeader, computed_checksum: int, chunk_files: list[str]) -> None:
    payload = {
        "header": {
            "console_name": header.console_name,
            "domestic_title": header.domestic_title,
            "overseas_title": header.overseas_title,
            "serial": header.serial,
            "checksum_in_header": f"0x{header.checksum:04X}",
            "checksum_computed": f"0x{computed_checksum:04X}",
            "rom_start": f"0x{header.rom_start:08X}",
            "rom_end": f"0x{header.rom_end:08X}",
        },
        "chunks": chunk_files,
    }
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def apply_byte_patches(data: bytes, patches: list[dict], strict: bool = True) -> bytes:
    """Apply byte patches with optional safety checks.

    Patch format:
    {"offset":"0x1234", "bytes":"AA BB", "expect":"12 34"}

    If `strict` is true, out-of-range writes and expectation mismatches raise errors.
    """
    out = bytearray(data)
    for p in patches:
        offset = int(p["offset"], 0)
        patch_bytes = bytes.fromhex(p["bytes"]) if isinstance(p["bytes"], str) else bytes(p["bytes"])

        if offset < 0 or offset + len(patch_bytes) > len(out):
            raise ValueError(f"Patch out of range at 0x{offset:X} length={len(patch_bytes)}")

        if "expect" in p:
            expect_bytes = bytes.fromhex(p["expect"]) if isinstance(p["expect"], str) else bytes(p["expect"])
            got = bytes(out[offset : offset + len(expect_bytes)])
            if strict and got != expect_bytes:
                raise ValueError(
                    f"Patch expectation mismatch at 0x{offset:X}: expected {expect_bytes.hex()} got {got.hex()}"
                )

        out[offset : offset + len(patch_bytes)] = patch_bytes
    return bytes(out)


def write_ips(base: bytes, modified: bytes, out_path: Path) -> None:
    # Minimal IPS encoder; chunk contiguous differences into records.
    if len(base) != len(modified):
        raise ValueError("IPS writer expects equal-size ROM images")

    out = bytearray(b"PATCH")
    i = 0
    n = len(base)
    while i < n:
        if base[i] == modified[i]:
            i += 1
            continue
        start = i
        while i < n and base[i] != modified[i] and (i - start) < 0xFFFF:
            i += 1
        chunk = modified[start:i]
        out.extend(start.to_bytes(3, "big"))
        out.extend(len(chunk).to_bytes(2, "big"))
        out.extend(chunk)

    out.extend(b"EOF")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_bytes(out)


def apply_ips(base: bytes, ips_bytes: bytes) -> bytes:
    if not ips_bytes.startswith(b"PATCH"):
        raise ValueError("Not an IPS file")
    pos = 5
    out = bytearray(base)
    while pos < len(ips_bytes):
        if ips_bytes[pos : pos + 3] == b"EOF":
            break
        offset = int.from_bytes(ips_bytes[pos : pos + 3], "big")
        pos += 3
        size = int.from_bytes(ips_bytes[pos : pos + 2], "big")
        pos += 2

        if size == 0:
            rle_size = int.from_bytes(ips_bytes[pos : pos + 2], "big")
            pos += 2
            value = ips_bytes[pos]
            pos += 1
            out[offset : offset + rle_size] = bytes([value]) * rle_size
        else:
            out[offset : offset + size] = ips_bytes[pos : pos + size]
            pos += size

    return bytes(out)

