; Autogenerated Genesis vector labels
cpu 68000

Vectors:
    dc.l vec_000 ; 0x00FFFE00
    dc.l vec_001 ; 0x0000450A
    dc.l vec_002 ; 0x00004500
    dc.l vec_003 ; 0x00004500
    dc.l vec_004 ; 0x00004500
    dc.l vec_005 ; 0x00004500
    dc.l vec_006 ; 0x00004500
    dc.l vec_007 ; 0x00004500
    dc.l vec_008 ; 0x00004500
    dc.l vec_009 ; 0x00004500
    dc.l vec_010 ; 0x00004500
    dc.l vec_011 ; 0x00004500
    dc.l vec_012 ; 0x00004500
    dc.l vec_013 ; 0x00004500
    dc.l vec_014 ; 0x00004500
    dc.l vec_015 ; 0x00004500
    dc.l vec_016 ; 0x00004500
    dc.l vec_017 ; 0x00004500
    dc.l vec_018 ; 0x00004500
    dc.l vec_019 ; 0x00004500
    dc.l vec_020 ; 0x00004500
    dc.l vec_021 ; 0x00004500
    dc.l vec_022 ; 0x00004500
    dc.l vec_023 ; 0x00004500
    dc.l vec_024 ; 0x00004500
    dc.l vec_025 ; 0x00004500
    dc.l vec_026 ; 0x00004500
    dc.l vec_027 ; 0x00004500
    dc.l vec_028 ; 0x0000483E
    dc.l vec_029 ; 0x00004500
    dc.l vec_030 ; 0x0000482E
    dc.l vec_031 ; 0x00004500
    dc.l vec_032 ; 0x00000000
    dc.l vec_033 ; 0x00000000
    dc.l vec_034 ; 0x00000000
    dc.l vec_035 ; 0x00000000
    dc.l vec_036 ; 0x00000000
    dc.l vec_037 ; 0x00000000
    dc.l vec_038 ; 0x00000000
    dc.l vec_039 ; 0x00000000
    dc.l vec_040 ; 0x00000000
    dc.l vec_041 ; 0x00000000
    dc.l vec_042 ; 0x00000000
    dc.l vec_043 ; 0x00000000
    dc.l vec_044 ; 0x00000000
    dc.l vec_045 ; 0x00000000
    dc.l vec_046 ; 0x00000000
    dc.l vec_047 ; 0x00000000
    dc.l vec_048 ; 0x00000000
    dc.l vec_049 ; 0x00000000
    dc.l vec_050 ; 0x00000000
    dc.l vec_051 ; 0x00000000
    dc.l vec_052 ; 0x00000000
    dc.l vec_053 ; 0x00000000
    dc.l vec_054 ; 0x00000000
    dc.l vec_055 ; 0x00000000
    dc.l vec_056 ; 0x00000000
    dc.l vec_057 ; 0x00000000
    dc.l vec_058 ; 0x00000000
    dc.l vec_059 ; 0x00000000
    dc.l vec_060 ; 0x00000000
    dc.l vec_061 ; 0x00000000
    dc.l vec_062 ; 0x00000000
    dc.l vec_063 ; 0x00000000
    dc.l vec_064 ; 0x53454741
    dc.l vec_065 ; 0x204D4547
    dc.l vec_066 ; 0x41204452
    dc.l vec_067 ; 0x49564520
    dc.l vec_068 ; 0x28432954
    dc.l vec_069 ; 0x2D323420
    dc.l vec_070 ; 0x31393931
    dc.l vec_071 ; 0x2E415547
    dc.l vec_072 ; 0x83898393
    dc.l vec_073 ; 0x834F838A
    dc.l vec_074 ; 0x83628354
    dc.l vec_075 ; 0x815B2020
    dc.l vec_076 ; 0x20202020
    dc.l vec_077 ; 0x20202020
    dc.l vec_078 ; 0x20202020
    dc.l vec_079 ; 0x20202020
    dc.l vec_080 ; 0x20202020
    dc.l vec_081 ; 0x20202020
    dc.l vec_082 ; 0x20202020
    dc.l vec_083 ; 0x20202020
    dc.l vec_084 ; 0x57415253
    dc.l vec_085 ; 0x4F4E4720
    dc.l vec_086 ; 0x20202020
    dc.l vec_087 ; 0x20202020
    dc.l vec_088 ; 0x20202020
    dc.l vec_089 ; 0x20202020
    dc.l vec_090 ; 0x20202020
    dc.l vec_091 ; 0x20202020
    dc.l vec_092 ; 0x20202020
    dc.l vec_093 ; 0x20202020
    dc.l vec_094 ; 0x20202020
    dc.l vec_095 ; 0x20202020
    dc.l vec_096 ; 0x474D2054
    dc.l vec_097 ; 0x2D323430
    dc.l vec_098 ; 0x3436202D
    dc.l vec_099 ; 0x30307E15
    dc.l vec_100 ; 0x4A202020
    dc.l vec_101 ; 0x20202020
    dc.l vec_102 ; 0x20202020
    dc.l vec_103 ; 0x20202020
    dc.l vec_104 ; 0x00000000
    dc.l vec_105 ; 0x0007FFFF
    dc.l vec_106 ; 0x00FF0000
    dc.l vec_107 ; 0x00FFFFFF
    dc.l vec_108 ; 0x5241F820
    dc.l vec_109 ; 0x00200001
    dc.l vec_110 ; 0x00203FFF
    dc.l vec_111 ; 0x20202020
    dc.l vec_112 ; 0x20202020
    dc.l vec_113 ; 0x20202020
    dc.l vec_114 ; 0x20202020
    dc.l vec_115 ; 0x20202020
    dc.l vec_116 ; 0x20202020
    dc.l vec_117 ; 0x20202020
    dc.l vec_118 ; 0x20202020
    dc.l vec_119 ; 0x20202020
    dc.l vec_120 ; 0x20202020
    dc.l vec_121 ; 0x20202020
    dc.l vec_122 ; 0x20202020
    dc.l vec_123 ; 0x20202020
    dc.l vec_124 ; 0x55202020
    dc.l vec_125 ; 0x20202020
    dc.l vec_126 ; 0x20202020
    dc.l vec_127 ; 0x20202020

vec_000: ; ROM 0x00FFFE00
    ; TODO: replace with disassembly
    rts

vec_001: ; ROM 0x0000450A
    ; TODO: replace with disassembly
    rts

vec_002: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_003: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_004: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_005: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_006: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_007: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_008: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_009: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_010: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_011: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_012: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_013: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_014: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_015: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_016: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_017: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_018: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_019: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_020: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_021: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_022: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_023: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_024: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_025: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_026: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_027: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_028: ; ROM 0x0000483E
    ; TODO: replace with disassembly
    rts

vec_029: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_030: ; ROM 0x0000482E
    ; TODO: replace with disassembly
    rts

vec_031: ; ROM 0x00004500
    ; TODO: replace with disassembly
    rts

vec_032: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_033: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_034: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_035: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_036: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_037: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_038: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_039: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_040: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_041: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_042: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_043: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_044: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_045: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_046: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_047: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_048: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_049: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_050: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_051: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_052: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_053: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_054: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_055: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_056: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_057: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_058: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_059: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_060: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_061: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_062: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_063: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_064: ; ROM 0x53454741
    ; TODO: replace with disassembly
    rts

vec_065: ; ROM 0x204D4547
    ; TODO: replace with disassembly
    rts

vec_066: ; ROM 0x41204452
    ; TODO: replace with disassembly
    rts

vec_067: ; ROM 0x49564520
    ; TODO: replace with disassembly
    rts

vec_068: ; ROM 0x28432954
    ; TODO: replace with disassembly
    rts

vec_069: ; ROM 0x2D323420
    ; TODO: replace with disassembly
    rts

vec_070: ; ROM 0x31393931
    ; TODO: replace with disassembly
    rts

vec_071: ; ROM 0x2E415547
    ; TODO: replace with disassembly
    rts

vec_072: ; ROM 0x83898393
    ; TODO: replace with disassembly
    rts

vec_073: ; ROM 0x834F838A
    ; TODO: replace with disassembly
    rts

vec_074: ; ROM 0x83628354
    ; TODO: replace with disassembly
    rts

vec_075: ; ROM 0x815B2020
    ; TODO: replace with disassembly
    rts

vec_076: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_077: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_078: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_079: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_080: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_081: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_082: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_083: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_084: ; ROM 0x57415253
    ; TODO: replace with disassembly
    rts

vec_085: ; ROM 0x4F4E4720
    ; TODO: replace with disassembly
    rts

vec_086: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_087: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_088: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_089: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_090: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_091: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_092: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_093: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_094: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_095: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_096: ; ROM 0x474D2054
    ; TODO: replace with disassembly
    rts

vec_097: ; ROM 0x2D323430
    ; TODO: replace with disassembly
    rts

vec_098: ; ROM 0x3436202D
    ; TODO: replace with disassembly
    rts

vec_099: ; ROM 0x30307E15
    ; TODO: replace with disassembly
    rts

vec_100: ; ROM 0x4A202020
    ; TODO: replace with disassembly
    rts

vec_101: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_102: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_103: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_104: ; ROM 0x00000000
    ; TODO: replace with disassembly
    rts

vec_105: ; ROM 0x0007FFFF
    ; TODO: replace with disassembly
    rts

vec_106: ; ROM 0x00FF0000
    ; TODO: replace with disassembly
    rts

vec_107: ; ROM 0x00FFFFFF
    ; TODO: replace with disassembly
    rts

vec_108: ; ROM 0x5241F820
    ; TODO: replace with disassembly
    rts

vec_109: ; ROM 0x00200001
    ; TODO: replace with disassembly
    rts

vec_110: ; ROM 0x00203FFF
    ; TODO: replace with disassembly
    rts

vec_111: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_112: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_113: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_114: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_115: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_116: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_117: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_118: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_119: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_120: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_121: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_122: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_123: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_124: ; ROM 0x55202020
    ; TODO: replace with disassembly
    rts

vec_125: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_126: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts

vec_127: ; ROM 0x20202020
    ; TODO: replace with disassembly
    rts
